### ISSUE TITLE
Screen garbled in Fullscreen

### ISSUE THREAD

**Issue by starquake** [IDemiurge/Eidolons#98]
When I first open up the game it looks like this:
![image](https://user-images.githubusercontent.com/1044544/59143818-63604580-89cf-11e9-8e0b-b24465946f50.png)

My resolution is 2560x1440p.

If I disable fullscreen it looks correctly. The setting isn't saved/reloaded though. I can open up a different issue for that if you want.

**Comment by IDemiurge** [comment]
OK, last version supports more resolutions in fullscreen, thanks for the screenshot!
